export const SIGN_UP_USER = 'SIGNUP_USER';
export const LOGIN_USER = 'SIGNIN_USER';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const PROMISE_RETURNED = 'PROMISE_RETURNED';
export const START_SESSION = 'START_SESSION';
export const END_SESSION = 'END_SESSION';
export const BANK_ACCOUNT_CREATE_LOADING = 'BANK_ACCOUNT_CREATE_LOADING';
export const BANK_ACCOUNT_CREATE_RESPONSE = 'BANK_ACCOUNT_CREATE_RESPONSE';

